<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-01-15T11:48:25-06:00" hostname="https://java-ability-1684-dev-ed.cs18.my.salesforce.com" tests="1" failures="1"  errors="0"  time="0.4">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Jan 15, 2020 11:48 AM"/>
            <property name="testExecutionTime" value="0.4 s"/>
            <property name="testTotalTime" value="0.4 s"/>
            <property name="commandTime" value="3.47 s"/>
            <property name="hostname" value="https://java-ability-1684-dev-ed.cs18.my.salesforce.com"/>
            <property name="orgId" value="00D1100000BwinsEAB"/>
            <property name="username" value="test-wc0mayhd3hmi@example.com"/>
            <property name="testRunId" value="7071100001o6zuF"/>
            <property name="userId" value="00511000006ptkJAAQ"/>
        </properties>
        <testcase name="shouldCreateMultipleConnectionsFromCustomValues" classname="formsConnectionRecordProcessTest" time="0.4">
            <failure message="System.AssertException: Assertion Failed: Expected: 1, Actual: 0"><![CDATA[Class.forms.ConnectionRecordProcessTest.shouldCreateMultipleConnectionsFromCustomValues: line 128, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
