<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2019-11-22T08:14:41-06:00" hostname="https://efficiency-energy-4546-dev-ed.cs41.my.salesforce.com" tests="5" failures="4"  errors="0"  time="1.55">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="5"/>
            <property name="passing" value="1"/>
            <property name="failing" value="4"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="20%"/>
            <property name="failRate" value="80%"/>
            <property name="testStartTime" value="Nov 22, 2019 8:14 AM"/>
            <property name="testExecutionTime" value="1.55 s"/>
            <property name="testTotalTime" value="1.55 s"/>
            <property name="commandTime" value="5.81 s"/>
            <property name="hostname" value="https://efficiency-energy-4546-dev-ed.cs41.my.salesforce.com"/>
            <property name="orgId" value="00D550000007L8REAU"/>
            <property name="username" value="test-ny6k239xml1j@example.com"/>
            <property name="testRunId" value="7075500001LJl10"/>
            <property name="userId" value="00555000003vDL9AAM"/>
        </properties>
        <testcase name="shouldCreateMultipleConnectionsFromCustomValues" classname="ConnectionRecordProcessTest" time="0.45">
            <failure message="System.AssertException: Assertion Failed: Expected: 1, Actual: 0"><![CDATA[Class.ConnectionRecordProcessTest.shouldCreateMultipleConnectionsFromCustomValues: line 130, column 1]]></failure>
        </testcase>
        <testcase name="shouldCreateMultipleConnectionsWithAppropriateStoreIds" classname="ConnectionRecordProcessTest" time="0.31">
            <failure message="System.AssertException: Assertion Failed: Expected: 0, Actual: 1"><![CDATA[Class.ConnectionRecordProcessTest.shouldCreateMultipleConnectionsWithAppropriateStoreIds: line 218, column 1]]></failure>
        </testcase>
        <testcase name="shouldCreateOpportunityConnectionFromCustomValue" classname="ConnectionRecordProcessTest" time="0.27">
            <failure message="System.AssertException: Assertion Failed: Expected: 0, Actual: 1"><![CDATA[Class.ConnectionRecordProcessTest.shouldCreateOpportunityConnectionFromCustomValue: line 87, column 1]]></failure>
        </testcase>
        <testcase name="shouldCreateOpportunityConnectionFromQuestionValue" classname="ConnectionRecordProcessTest" time="0.26">
            <failure message="System.AssertException: Assertion Failed: Expected: 1, Actual: 0"><![CDATA[Class.ConnectionRecordProcessTest.shouldCreateOpportunityConnectionFromQuestionValue: line 175, column 1]]></failure>
        </testcase>
        <testcase name="shouldUpdateProcessToFailed" classname="ConnectionRecordProcessTest" time="0.25">
        </testcase>
    </testsuite>
</testsuites>
